---
security_group_name: db_security_group
region_name: us-east-1
IAM _groupname: ansible-group
keypair_name: ec2-test
#access_key:xxxxxxxxxx
#secret_key: xxxxxxxxxxxxxx
cidr: 10.22.1.0/24
Private_Subnet_name: Private_Subnet_DB__server
requestor_name: Naveen
env_name: DEV
resource_name: PRIVATE-SUBNET-DB-SERVERS
back_up: NA
business_hours: EST 00-00
automate: OPT OUT
owner: naveen1228@gmail.com
cost_center_name: CLOUD
customer_name: Devops world
