- name: provision an Application server Ec2 Instance
  hosts: localhost
  connection: local
  tags: provisioning
  vars_files:
      - group_vars/app-ec2.yml
  vars:
      instance_type: "{{ instancetype }}"
      image: "{{ AMI }}"
      security_group: "{{ security_group_name }}" 
      region: "{{ region_name }}"
      gpname: "{{ IAM_groupname }}"
      keypair: "{{ keypair_name }}"
      state: present
      number: 1
#      aws_access_key: "{{ aws_access_key }}"
#      aws_secret_key: "{{ aws_secret_key }}"
      aws_tags:
         NAME: "{{ requestor_name }}"
         ENVIRONMENT: "{{ env_name }}"
         RESOURCE ID: "{{ resource_name }}"
         BACK UP: "{{ back_up }}"
         BUSINESS HOURS: "{{ business_hours }}"
         AUTOMATE: "{{ automate }}"
         OWNER: "{{ owner }}"
         COST CENTER: "{{ cost_center_name }}"
         CUSTOMER: "{{ customer_name }}"
  tasks:
    - name: Create Application Server instance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{instance_type}}"
#      aws_access_key: "{{ aws_access_key }}"
#      aws_secret_key: "{{ aws_secret_key }}"
         image: "{{image}}"
         region: "{{region}}"
         wait: true
         exact_count: "{{number}}"
         count_tag:
           Name: "{{gpname}}"
         instance_tags: "{{ aws_tags }}"
         group_id: "{{ group_id }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         key_name: "{{keypair}}"
      register: ec2_result

    - debug:
        msg: "app-server  public ip address is: {{ec2_result.instances[0].public_ip}}"

    - name: wait for ssh to come up
      local_action: wait_for
                    host={{ec2_result.instances[0].public_ip}}
                    port=22
                    state=started
      with_items: ec2.instances

